param(
  [string]$In = 'docs/marketplace/assets-index_EN.md',
  [string]$Out = 'docs/marketplace/tbd-ui-report_EN.md'
)

$ErrorActionPreference = 'Stop'

try {
  [Console]::OutputEncoding = New-Object System.Text.UTF8Encoding($false)
} catch {}

$repoRoot = Split-Path -Parent $PSScriptRoot
Set-Location -LiteralPath $repoRoot

$inPath = Join-Path $repoRoot $In
if (-not (Test-Path -LiteralPath $inPath -PathType Leaf)) {
  throw ('Missing input file: ' + $In)
}

# Read as UTF-8 (no BOM) best-effort; file may have BOM too.
$linesIn = Get-Content -LiteralPath $inPath

$hits = New-Object System.Collections.Generic.List[object]
$currentH1 = ''
$currentH2 = ''
$currentH3 = ''

for ($i = 0; $i -lt $linesIn.Count; $i++) {
  $line = $linesIn[$i]
  $trim = $line.Trim()

  if ($trim -match '^#\s+(.+)$') {
    $currentH1 = $Matches[1].Trim()
    $currentH2 = ''
    $currentH3 = ''
    continue
  }
  if ($trim -match '^##\s+(.+)$') {
    $currentH2 = $Matches[1].Trim()
    $currentH3 = ''
    continue
  }
  if ($trim -match '^###\s+(.+)$') {
    $currentH3 = $Matches[1].Trim()
    continue
  }

  # Match both placeholders.
  if ($line -match '\[FILL\]' -or $line -match '\bTBD_UI\b') {
    $hits.Add([pscustomobject]@{
      LineNumber = ($i + 1)
      H1 = $currentH1
      H2 = $currentH2
      H3 = $currentH3
      Text = $trim
    })
  }
}

$linesOut = New-Object System.Collections.Generic.List[string]
$linesOut.Add('# TBD_UI / [FILL] report (auto-generated)')
$linesOut.Add('')
$linesOut.Add('Generated by: scripts/marketplace-tbd-ui-report.ps1')
$linesOut.Add(('Time (local): ' + (Get-Date).ToString('yyyy-MM-dd HH:mm (K)')))
$linesOut.Add(('Input: ' + $In))
$linesOut.Add('')
$linesOut.Add('Purpose: help you quickly find UI-dependent fields to verify in Fiverr/Upwork/Toptal UI and then replace in assets-index_EN.md.')
$linesOut.Add('')

if (-not $hits -or $hits.Count -eq 0) {
  $linesOut.Add('OK: No TBD_UI / [FILL] placeholders found.')
  $linesOut.Add('')
  $linesOut.Add('REPORT_OK')
  $linesOut.Add('')
} else {
  $linesOut.Add(('Found placeholders: ' + $hits.Count))
  $linesOut.Add('')
  $linesOut.Add('- Format: line | context | text')
  $linesOut.Add('')

  foreach ($h in $hits) {
    $ctxParts = @()
    if ($h.H1) { $ctxParts += $h.H1 }
    if ($h.H2) { $ctxParts += $h.H2 }
    if ($h.H3) { $ctxParts += $h.H3 }
    $ctx = ($ctxParts -join ' > ')
    if (-not $ctx) { $ctx = '(no heading context)' }

    $linesOut.Add(('- line ' + $h.LineNumber + ' | ' + $ctx + ' | ' + $h.Text))
  }

  $linesOut.Add('')
  $linesOut.Add('Next: open the platform UI, verify the exact limits/policies, then replace TBD_UI/[FILL] in assets-index_EN.md.')
  $linesOut.Add('')
  $linesOut.Add('REPORT_OK')
  $linesOut.Add('')
}

$outPath = Join-Path $repoRoot $Out
$outDir = Split-Path -Parent $outPath
if (-not (Test-Path -LiteralPath $outDir)) {
  New-Item -ItemType Directory -Path $outDir | Out-Null
}

# UTF-8 with BOM (keeps Windows editors happy)
$utf8Bom = New-Object System.Text.UTF8Encoding($true)
[System.IO.File]::WriteAllLines($outPath, $linesOut, $utf8Bom)

Write-Host ('Wrote: ' + $Out)
Write-Host 'REPORT_OK'
