param(
  [string]$Out = 'docs/marketplace/assets-sizes_EN.md'
)

$ErrorActionPreference = 'Stop'

try {
  [Console]::OutputEncoding = New-Object System.Text.UTF8Encoding($false)
} catch {}

$repoRoot = Split-Path -Parent $PSScriptRoot
Set-Location -LiteralPath $repoRoot

function GetFileRows([string]$glob, [string]$label) {
  $items = Get-ChildItem -Path $glob -File -ErrorAction SilentlyContinue
  foreach ($it in $items) {
    $bytes = [int64]$it.Length
    $kb = [Math]::Round($bytes / 1KB, 1)
    $mb = [Math]::Round($bytes / 1MB, 2)
    [pscustomobject]@{
      Group = $label
      Path  = $it.FullName.Substring($repoRoot.Length + 1).Replace('\','/')
      Bytes = $bytes
      KB    = $kb
      MB    = $mb
    }
  }
}

$rows = @()
$rows += GetFileRows -glob 'docs/assets/*.png' -label 'docs/assets (png)'
$rows += GetFileRows -glob 'docs/assets/*.gif' -label 'docs/assets (gif)'
$rows += GetFileRows -glob 'dist/*.zip' -label 'dist (zip)'
$rows += GetFileRows -glob 'lite/dist/*.zip' -label 'lite/dist (zip)'

if (-not $rows -or $rows.Count -eq 0) {
  throw 'No assets found to report. Expected docs/assets/*.(png|gif) or dist/*.zip'
}

$rows = $rows | Sort-Object -Property @(
  @{ Expression = 'Group'; Ascending = $true },
  @{ Expression = 'MB'; Descending = $true },
  @{ Expression = 'Path'; Ascending = $true }
)

$lines = New-Object System.Collections.Generic.List[string]
$lines.Add('# Asset size report (auto-generated)')
$lines.Add('')
$lines.Add('Generated by: scripts/marketplace-asset-report.ps1')
$lines.Add(('Time (local): ' + (Get-Date).ToString('yyyy-MM-dd HH:mm (K)')))
$lines.Add('')
$lines.Add('This file helps you paste/upload the right assets on Fiverr/Upwork without hitting size limits.')
$lines.Add('')
$lines.Add('## Files')
$lines.Add('')
$lines.Add('- Format: group | path | bytes | MB')
$lines.Add('')

foreach ($r in $rows) {
  $lines.Add(('- ' + $r.Group + ' | ' + $r.Path + ' | ' + $r.Bytes + ' | ' + $r.MB + ' MB'))
}

$sumBytes = ($rows | Measure-Object -Property Bytes -Sum).Sum
$lines.Add('')
$lines.Add('## Summary')
$lines.Add('')
$lines.Add(('- Total files: ' + $rows.Count))
$lines.Add(('- Total bytes: ' + $sumBytes))
$lines.Add(('- Total MB: ' + ([Math]::Round($sumBytes / 1MB, 2)) + ' MB'))
$lines.Add('')
$lines.Add('NOTE: If a platform rejects an upload due to size, consider:')
$lines.Add('- Use PNG instead of GIF (or reduce GIF frames).')
$lines.Add('- Use Lite demo link instead of uploading a big ZIP.')
$lines.Add('')
$lines.Add('REPORT_OK')
$lines.Add('')

$outPath = Join-Path $repoRoot $Out
$outDir = Split-Path -Parent $outPath
if (-not (Test-Path -LiteralPath $outDir)) {
  New-Item -ItemType Directory -Path $outDir | Out-Null
}

# UTF-8 with BOM (keeps Windows editors happy)
$utf8Bom = New-Object System.Text.UTF8Encoding($true)
[System.IO.File]::WriteAllLines($outPath, $lines, $utf8Bom)

Write-Host ('Wrote: ' + $Out)
Write-Host 'REPORT_OK'
